### ISSUE TITLE
Long teardown (20s) with VidiU and GStreamer 1.0

### ISSUE THREAD

**Issue by wmanley** [drothlis/stb-tester#111]
With GStreamer 1.0 there is a 20s delay during VidiU pipeline shutdown.  This is probably a GStreamer bug.  Investigation required.

**Comment by wmanley** [comment]
As this is a bug in GStreamer rather than stb-tester itself I'm tempted to say that this issue (as well as #150) should be closed.  Thoughts?

**Comment by drothlis** [comment]
Closing upstream GStreamer / librtmp bugs that we don't intend to fix since it doesn't affect the hardware we use.
