### ISSUE TITLE
`wait_for_match` and `press_until_match` should take `region` parameter for underlying `match` call

### ISSUE THREAD

**Issue by LewisHaley** [drothlis/stb-tester#252]
It would be very useful if the higher-level functions which called `match` allowed the user to pass through a `region` parameter to `match`.

**Comment by wmanley** [comment]
Make a pull-request and I'd merge it.

**Comment by drothlis** [comment]
Closing wishlist issues. We'll accept a pull request with this implemented. Thanks for taking the time to point out this inconsistency. :-)
