### ISSUE TITLE
stbt batch report page breaks if the contents of a cell in the table's first row are too long

### ISSUE THREAD

**Issue by szemate** [drothlis/stb-tester#257]
The javascript of `index.html` breaks with an error in `tablequeryjs` if any of the cells of the test results' table is longer than ~150 characters. As a result it is not possible to open test run details. This issue is easy to reproduce by inserting a long text into the "notes" column and reloading the page.

**Comment by drothlis** [comment]
Thanks for the bug report.

* What was the error?
* What version did you test? (I want to know if this is a regression since v0.21.)

**Comment by aiman** [comment]
Issue was reproduced on stbt 0.21 but also known to affect stbt 0.18 so not a regression.

**Comment by drothlis** [comment]
> Issue was reproduced on stbt 0.21

That doesn't sound right. In 0.21 the notes column is truncated to ~30 characters, so length of the notes field wouldn't be able to trigger this.

I couldn't reproduce this on 0.21 but I've reproduced it on master.

> What was the error message?

To answer my own question: The error message is completely unhelpful:

    TypeError: this._d is undefined     tablequery.min.js:44

Unfortunately there doesn't seem to be an un-minified version of tablequeryjs available from the CDN.

**Comment by drothlis** [comment]
After jumping through a whole bunch of hoops (which I may document later if the exercise turns out to be useful) to get an unminified version, the error is in moment.js and is no more enlightening:

```
(function (undefined) {
[...]
    extend(moment.fn = Moment.prototype, {
[...]
        isValid : function () {
[...]
                    this._isValid = !isNaN(this._d.getTime());
[...]
```

**Comment by drothlis** [comment]
It looks like this is related to the bug where tablequery tries to figure out the column types by looking at the contents of the first row (after the table header). I could only reproduce this if the long table cell was in the first row.

**Comment by szemate** [comment]
> I could only reproduce this if the long table cell was in the first row.

Yes it seems that it only affects the first row. Sorry that I haven't noticed it.

**Comment by aiman** [comment]
>  In 0.21 the notes column is truncated to ~30 characters

It is `extra-columns` in particular that we are having a problem with.

**Comment by szemate** [comment]
Thanks for the quick fix!

**Comment by drothlis** [comment]
> > In 0.21 the notes column is truncated to ~30 characters
>
> It is extra-columns in particular that we are having a problem with.

You're right -- In 0.21 we truncated notes but not extra-columns. I didn't realise that. Oh well now we don't truncate anything in html, we use CSS for the truncation (which allows tablequery to work on the entire text).
